CREATE OR REPLACE VIEW VIEW_ACCESS_TOKEN_ROLES
(USER_PROFILE_ID,IS_ADMIN,USERNAME,TOKEN,SIGN_IN_ID,SESSION_ID,CHANNEL_ID,DEVICE_TYPE,COMPANY_ID,"TYPE",PLATFORM, APP_ID,ROLE_NAME,UPDATED_DATE,PUBLIC_KEY)
AS
SELECT DISTINCT
uat.USER_PROFILE_ID,
(SELECT up.IS_ADMIN FROM USER_PROFILE up WHERE up.USER_PROFILE_ID = uat.USER_PROFILE_ID) AS IS_ADMIN,
(SELECT up.USERNAME FROM USER_PROFILE up WHERE up.USER_PROFILE_ID = uat.USER_PROFILE_ID) AS USERNAME,
uat.TOKEN,
uat.SIGN_IN_ID,
uat.SESSION_ID,
uat.CHANNEL_ID,
uat.DEVICE_TYPE,
uat.COMPANY_ID,
uat.TYPE,
(SELECT ci.PLATFORM FROM CLIENT_INFO ci WHERE ci.TOKEN = uat.TOKEN) AS PLATFORM,
(SELECT ci.APP_ID FROM CLIENT_INFO ci WHERE ci.TOKEN = uat.TOKEN) AS APP_ID,
(SELECT rc.NAME FROM ROLE_COMPANY rc WHERE rc.ROLE_ID = st.ROLE_ID) AS ROLE_NAME,
uat.UPDATED_DATE,
uat.PUBLIC_KEY
FROM USER_ACCESS_TOKEN uat
LEFT JOIN STAFF st ON st.USER_PROFILE_ID = uat.USER_PROFILE_ID AND st.COMPANY_ID = uat.COMPANY_ID  AND st.IS_DELETED = 0;