CREATE OR REPLACE VIEW VIEW_STATISTIC_VACANCY_SEAT
(REPORT_DATE, STAFF_ID , COUNT_RESULT, TYPE)
AS
--     TYPE: 1 - Open seat; 2 - Closed seat; 3 - Candidate processed; ...
    SELECT vs.CREATED_DATE AS REPORT_DATE, vs.RESPONSIBLE_STAFF_ID AS STAFF_ID , COUNT(vs.ID) AS RESULT_COUNT, 1 AS TYPE
    FROM VACANCY_SEAT vs
    WHERE vs.RESPONSIBLE_STAFF_ID IS NOT NULL
    GROUP BY vs.CREATED_DATE, vs.RESPONSIBLE_STAFF_ID

    UNION ALL

    SELECT vs.CLOSED_DATE AS REPORT_DATE, vs.CLOSED_STAFF_ID AS STAFF_ID , COUNT(vs.ID) AS RESULT_COUNT, 2 AS TYPE
    FROM VACANCY_SEAT vs
    WHERE vs.CLOSED_STAFF_ID IS NOT NULL
    GROUP BY vs.CLOSED_DATE, vs.CLOSED_STAFF_ID;

