DECLARE
    CURSOR aptm_cursor IS SELECT * FROM APPOINTMENT WHERE IS_DELETED=0;
BEGIN
FOR aptm IN aptm_cursor
  LOOP
  UPDATE APPOINTMENT ap
    SET ap.APPOINTMENT_DATE = (
        SELECT MAX(atr.APPOINTMENT_TIME) + INTERVAL '59' MINUTE + INTERVAL '59' SECOND
        FROM APPOINTMENT_TIME_RANGE atr
        WHERE atr.APPOINTMENT_ID=aptm.APPOINTMENT_ID)
    WHERE ap.APPOINTMENT_ID=aptm.APPOINTMENT_ID;
  END LOOP;  
END;