package com.qooco.boost.constants;

public interface AttributeEventType {
    int EVT_SHARED_GITF_CODE = 1;
    int EVT_REDEEMED_GITF_CODE = 2;
    int EVT_OPEN_ALL_TABS_IN_MAIN_MENU = 3;
    int EVT_SHARED_CODE_ACTIVATED = 4;
    int EVT_ENTER_APPLICATION = 5;
    int EVT_ENTER_APP_EVERYDAY_FOR_3_DAYS = 6;
    int EVT_ENTER_APP_EVERYDAY_FOR_7_DAYS = 7;
    int EVT_ENTER_APP_EVERYDAY_FOR_14_DAYS = 8;
    int EVT_GET_NEW_ASSESSMENT = 9;
    int EVT_GET_MORE_THAN_TWO_DIFFERENT_ASSESSMENTS = 10;
    int EVT_RENEW_ASSESSMENT = 11;
    int EVT_RENEW_ASSESSMENT_MORE_THAN_TWO_TIMES = 12;
    int EVT_IMPROVE_ASSESSMENT_RESULT = 13;
    int EVT_GET_A_HIGH_EMPATHY_TEST_SCORE = 14;
    int EVT_FILL_THE_PROFILE_IN_ONE_SESSION = 15;
    int EVT_FILL_ALL_PROFILE_FIELDS = 16;
    int EVT_COMPLETE_ALL_PROFILE_STEPS = 17;
    int EVT_SEND_MESSAGE = 18;
}
