BEGIN
  DECLARE
  seqval NUMBER;
  BEGIN
    SELECT NVL(MAX(WORKING_HOUR_ID),0)  + 1
    INTO seqval
    FROM WORKING_HOUR;
   
  
    execute immediate('CREATE SEQUENCE WORKING_HOUR_SEQ MINVALUE 1 START WITH '||seqval||' INCREMENT BY 1 ORDER CACHE 20');
  END;
END;
/