BEGIN
  DECLARE
  seqval NUMBER;
  BEGIN
    SELECT NVL(MAX(APPOINTMENT_ID),0)  + 1
    INTO seqval
    FROM APPOINTMENT_DETAIL;
   
  
    execute immediate('CREATE SEQUENCE APPOINTMENT_DETAIL_SEQ MINVALUE 1 START WITH '||seqval||' INCREMENT BY 1 ORDER CACHE 20');
  END;
END;
/