BEGIN
  DECLARE
  seqval NUMBER;
  BEGIN
    SELECT NVL(MAX(QUALIFICATION_ID),0)  + 1
    INTO seqval
    FROM USER_QUALIFICATION;
   
  
    execute immediate('CREATE SEQUENCE USER_QUALIFICATION_SEQ MINVALUE 1 START WITH '||seqval||' INCREMENT BY 1 ORDER CACHE 20');
  END;
END;
/