BEGIN
  DECLARE
  seqval NUMBER;
  BEGIN
    SELECT NVL(MAX(PERMISSION_ID),0)  + 1
    INTO seqval
    FROM PERMISSION;
   
  
    execute immediate('CREATE SEQUENCE PERMISSION_SEQ MINVALUE 1 START WITH '||seqval||' INCREMENT BY 1 ORDER CACHE 20');
  END;
END;
/