BEGIN
  DECLARE
  seqval NUMBER;
  BEGIN
    SELECT NVL(MAX(REFERRAL_CODE_ID),0)  + 1
    INTO seqval
    FROM REFERRAL_CODE;
   
  
    execute immediate('CREATE SEQUENCE REFERRAL_CODE_SEQ MINVALUE 1 START WITH '||seqval||' INCREMENT BY 1 ORDER CACHE 20');
  END;
END;
/