BEGIN
  DECLARE
  seqval NUMBER;
  BEGIN
    SELECT NVL(MAX(COMPANY_ID),0)  + 1
    INTO seqval
    FROM COMPANY;
   
  
    execute immediate('CREATE SEQUENCE COMPANY_SEQ MINVALUE 1 START WITH '||seqval||' INCREMENT BY 1 ORDER CACHE 20');
  END;
END;
/