BEGIN
  DECLARE
  seqval NUMBER;
  BEGIN
    SELECT NVL(MAX(LANGUAGE_ID),0)  + 1
    INTO seqval
    FROM "LANGUAGE";
   
  
    execute immediate('CREATE SEQUENCE LANGUAGE_SEQ MINVALUE 1 START WITH '||seqval||' INCREMENT BY 1 ORDER CACHE 20');
  END;
END;
/