BEGIN
  DECLARE
  seqval NUMBER;
  BEGIN
    SELECT NVL(MAX(CURRENCY_ID),0)  + 1
    INTO seqval
    FROM CURRENCY;
   
  
    execute immediate('CREATE SEQUENCE CURRENCY_SEQ MINVALUE 1 START WITH '||seqval||' INCREMENT BY 1 ORDER CACHE 20');
  END;
END;
/