BEGIN
  DECLARE
  seqval NUMBER;
  BEGIN
    SELECT NVL(MAX(REFERRAL_ASSESSMENT_ID),0)  + 1
    INTO seqval
    FROM REFERRAL_CLAIM_ASSESSMENT;
   
  
    execute immediate('CREATE SEQUENCE REFERRAL_ASSESSMENT_SEQ MINVALUE 1 START WITH '||seqval||' INCREMENT BY 1 ORDER CACHE 20');
  END;
END;
/