BEGIN
  DECLARE
  seqval NUMBER;
  BEGIN
    SELECT NVL(MAX(BENEFIT_ID),0)  + 1
    INTO seqval
    FROM BENEFIT;
   
  
    execute immediate('CREATE SEQUENCE BENEFIT_SEQ MINVALUE 1 START WITH '||seqval||' INCREMENT BY 1 ORDER CACHE 20');
  END;
END;
/