BEGIN
  DECLARE
  seqval NUMBER;
  BEGIN
    SELECT NVL(MAX(USER_LANGUAGE_ID),0)  + 1
    INTO seqval
    FROM USER_LANGUAGE;
   
  
    execute immediate('CREATE SEQUENCE USER_LANGUAGE_SEQ MINVALUE 1 START WITH '||seqval||' INCREMENT BY 1 ORDER CACHE 20');
  END;
END;
/