BEGIN
  DECLARE
  seqval NUMBER;
  BEGIN
    SELECT NVL(MAX(REQUIRED_ASSESSMENT_ID),0)  + 1
    INTO seqval
    FROM REQUIRED_ASSESSMENT;
   
  
    execute immediate('CREATE SEQUENCE REQUIRED_ASSESSMENT_SEQ MINVALUE 1 START WITH '||seqval||' INCREMENT BY 1 ORDER CACHE 20');
  END;
END;
/