BEGIN
  DECLARE
  seqval NUMBER;
  BEGIN
    SELECT NVL(MAX(STAFF_ID),0)  + 1
    INTO seqval
    FROM STAFF;
   
  
    execute immediate('CREATE SEQUENCE STAFF_SEQ MINVALUE 1 START WITH '||seqval||' INCREMENT BY 1 ORDER CACHE 20');
  END;
END;
/