BEGIN
  DECLARE
  seqval NUMBER;
  BEGIN
    SELECT NVL(MAX(USER_PREVIOUS_POSITION_ID),0)  + 1
    INTO seqval
    FROM USER_PREVIOUS_POSITION;
   
  
    execute immediate('CREATE SEQUENCE USER_PREVIOUS_POSITION_SEQ MINVALUE 1 START WITH '||seqval||' INCREMENT BY 1 ORDER CACHE 20');
  END;
END;
/