BEGIN
  DECLARE
  seqval NUMBER;
  BEGIN
    SELECT NVL(MAX(USER_DESIRED_HOUR_ID),0)  + 1
    INTO seqval
    FROM USER_DESIRED_HOUR;
   
  
    execute immediate('CREATE SEQUENCE USER_DESIRED_HOUR_SEQ MINVALUE 1 START WITH '||seqval||' INCREMENT BY 1 ORDER CACHE 20');
  END;
END;
/