BEGIN
  DECLARE
  seqval NUMBER;
  BEGIN
    SELECT NVL(MAX(USER_FIT_LANGUAGE_ID),0)  + 1
    INTO seqval
    FROM USER_FIT_LANGUAGE;
   
  
    execute immediate('CREATE SEQUENCE USER_FIT_LANGUAGE_SEQ MINVALUE 1 START WITH '||seqval||' INCREMENT BY 1 ORDER CACHE 20');
  END;
END;
/