BEGIN
  DECLARE
  seqval NUMBER;
  BEGIN
    SELECT NVL(MAX(REFERRAL_REDEEM_ID),0)  + 1
    INTO seqval
    FROM REFERRAL_REDEEM;
   
  
    execute immediate('CREATE SEQUENCE REFERRAL_REDEEM_SEQ MINVALUE 1 START WITH '||seqval||' INCREMENT BY 1 ORDER CACHE 20');
  END;
END;
/