CREATE OR REPLACE TRIGGER SLOT_AFTER_CREATE_VACANCY
AFTER INSERT ON VACANCY
FOR EACH ROW
DECLARE
v_id NUMBER;
v_seat_open NUMBER;
BEGIN

	v_seat_open := 1;
    IF :NEW.NUMBER_OF_SEAT > 0 THEN
        FOR i in 1 .. :NEW.NUMBER_OF_SEAT LOOP
        SELECT VACANCY_SEAT_SEQ.nextval
        INTO v_id
        FROM dual;

        INSERT INTO VACANCY_SEAT (ID, VACANCY_ID, STATUS, CREATED_DATE, RESPONSIBLE_STAFF_ID)
        VALUES(v_id, :NEW.VACANCY_ID, v_seat_open, :NEW.CREATED_DATE, :NEW.CONTACT_PERSON_ID);
        END LOOP;
    END IF;
END SLOT_AFTER_CREATE_VACANCY;
/