CREATE OR REPLACE FUNCTION IS_SUSPEND_RANGE( VACANCY_STATUS in NUMBER, START_DATE in TIMESTAMP , SUSPEND_DAYS in NUMBER, NOW_TIME in TIMESTAMP)
RETURN NUMBER IS SUSPEND_STATUS NUMBER;
BEGIN
	DECLARE TEMP_STATUS NUMBER;
	BEGIN
	    TEMP_STATUS := 1;
		IF VACANCY_STATUS = 1 AND START_DATE IS NOT NULL AND SUSPEND_DAYS > 0 THEN
		    IF NOW_TIME > START_DATE + numtodsinterval( SUSPEND_DAYS, 'day' ) THEN TEMP_STATUS := 1;
		    ELSE TEMP_STATUS := 2;
		    END IF;
		ELSIF VACANCY_STATUS = 2 THEN TEMP_STATUS := 2;
		ELSIF VACANCY_STATUS = 3 THEN TEMP_STATUS := 3;
		END IF;
	SUSPEND_STATUS := TEMP_STATUS;
	RETURN SUSPEND_STATUS;
	END;
END IS_SUSPEND_RANGE;
/