CREATE OR REPLACE FUNCTION START_DAY_UTC_IN_OFFSET
(INPUT_DATE DATE, TIME_OFFSET VARCHAR2)
RETURN DATE
IS
BEGIN
  RETURN sys_extract_utc(from_tz(cast(trunc(INPUT_DATE) AS TIMESTAMP), TIME_OFFSET));
END START_DAY_UTC_IN_OFFSET;
/