CREATE OR REPLACE FUNCTION GET_STATUS_OF_GIFT_BY_DURATION
(ACTIVE_DATE TIMESTAMP, EXPIRED_DATE TIMESTAMP, NOW_TIME TIMESTAMP)
RETURN NUMBER
IS
ORDER_STATUS NUMBER;
BEGIN
	IF NOW_TIME <= EXPIRED_DATE AND NOW_TIME >= ACTIVE_DATE THEN
      ORDER_STATUS := 0;
  	ELSIF  NOW_TIME < ACTIVE_DATE THEN
      ORDER_STATUS := 1;
  	ELSE
      ORDER_STATUS := 2;
 	END IF;
  	RETURN ORDER_STATUS;
END GET_STATUS_OF_GIFT_BY_DURATION;
/